# Generated by Django 4.2.28 on 2026-02-26 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_snapshot', models.CharField(max_length=255)),
                ('om_number', models.CharField(max_length=50, verbose_name='Nº OM')),
                ('execution_date', models.DateField(default=django.utils.timezone.localdate)),
                ('executor_name', models.CharField(max_length=120)),
                ('t1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('t2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('t3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('m1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('m2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pulses_per_turn_1', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('pulses_per_turn_2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('pulses_per_turn_3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ibm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('abw_1', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('abw_2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('abw_3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tare_1', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tare_2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tare_3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('applied_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('bridge_length', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('belt_length', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('il_before_ti', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('il_before_tf', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('il_after_ti', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('il_after_tf', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('check_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('kor', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('observation', models.TextField(blank=True)),
                ('validator_name', models.CharField(blank=True, max_length=120)),
                ('validator_signature_data', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_validation', 'Pendente validacao'), ('approved', 'Aprovado'), ('sent_to_sap', 'Enviado SAP')], default='draft', max_length=32)),
                ('sap_status', models.CharField(choices=[('not_started', 'Nao iniciado'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='not_started', max_length=24)),
                ('sap_attachment_id', models.CharField(blank=True, max_length=120)),
                ('sap_response_message', models.TextField(blank=True)),
                ('sap_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='inspecoes.equipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
