# Generated by Django 4.2.28 on 2026-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='belt_speed_v',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='calculated_flow_ic',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='error_after_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='error_before_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='sector',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='span_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='standards_used',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='validator_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
