# Generated by Django 4.2.28 on 2026-02-26 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0002_formsubmission_belt_speed_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Informe um ou mais e-mails separados por virgula, ponto e virgula ou quebra de linha.', verbose_name='E-mails para notificacao'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='revisit_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de dias para nova verificacao/ajuste do equipamento.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Periodicidade da nova visita (dias)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='mark_distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='speed_characteristic_b04',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tag',
            field=models.CharField(max_length=80, unique=True, verbose_name='TAG'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='om_number',
            field=models.CharField(max_length=50, verbose_name='Nº OM'),
        ),
    ]
