# Generated by Django 4.2.28 on 2026-03-02 16:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0003_equipment_notification_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Limite de aceitacao para o erro final (%). Ex.: 1.000', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Criterio de aceitacao (%)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='expanded_uncertainty_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Opcional.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Incerteza expandida (%)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6, verbose_name='Criterio de aceitacao (%)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='expanded_uncertainty_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Incerteza expandida (%)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technician_2_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technician_2_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technician_3_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technician_3_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
