# Generated by Django 4.2.28 on 2026-03-02 19:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0004_equipment_acceptance_criterion_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='sector_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='sector_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technician_1_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Limite de aceitacao para o erro final (%). Ex.: 1.000', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Critério de aceitação (%)'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=6, verbose_name='Critério de aceitação (%)'),
        ),
    ]
