# Generated by Django 4.2.28 on 2026-03-03 19:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecoes', '0005_formsubmission_sector_2_formsubmission_sector_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Limite de aceitação para o erro final (%). Ex.: 1,0', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Critério de aceitação (%)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Informe um ou mais e-mails separados por vírgula, ponto e vírgula ou quebra de linha.', verbose_name='E-mails para notificação'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='revisit_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de dias para nova verificação/ajuste do equipamento.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Periodicidade da nova visita (dias)'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='sap_status',
            field=models.CharField(choices=[('not_started', 'Não iniciado'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='not_started', max_length=24),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending_validation', 'Pendente validação'), ('approved', 'Aprovado'), ('sent_to_sap', 'Enviado SAP')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='PortalUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, help_text='Se vazio, usa o username do usuário.', max_length=50, verbose_name='Matrícula')),
                ('can_edit', models.BooleanField(default=False, help_text='Se marcado, pode criar/editar/validar/enviar para SAP.', verbose_name='Pode editar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso ao portal',
                'verbose_name_plural': 'Acessos ao portal',
                'ordering': ['user__username'],
            },
        ),
    ]
