# Generated by Django 4.2.28 on 2026-03-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0006_alter_equipment_acceptance_criterion_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_edit_forms',
            field=models.BooleanField(default=False, help_text='Permite criar, editar, validar formulários e enviar para SAP.', verbose_name='Editar formulários'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_view_deadlines',
            field=models.BooleanField(default=True, help_text='Permite acessar a tela de prazos dos equipamentos.', verbose_name='Acessar tela Prazos'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_view_forms',
            field=models.BooleanField(default=True, help_text='Permite acessar formulários (detalhe, PDF e fluxo de formulário).', verbose_name='Acessar tela Formulários'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_view_history',
            field=models.BooleanField(default=True, help_text='Permite acessar a tela de histórico de formulários.', verbose_name='Acessar tela Histórico'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Compatibilidade com versões anteriores.', verbose_name='Pode editar (legado)'),
        ),
    ]
