# Generated by Django 4.2.28 on 2026-03-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0006_alter_equipment_acceptance_criterion_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_edit_forms',
            field=models.BooleanField(default=False, help_text='Permite criar, editar, validar formulÃ¡rios e enviar para SAP.', verbose_name='Editar formulÃ¡rios'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_view_deadlines',
            field=models.BooleanField(default=True, help_text='Permite acessar a tela de prazos dos equipamentos.', verbose_name='Acessar tela Prazos'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_view_forms',
            field=models.BooleanField(default=True, help_text='Permite acessar formulÃ¡rios (detalhe, PDF e fluxo de formulÃ¡rio).', verbose_name='Acessar tela FormulÃ¡rios'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='can_view_history',
            field=models.BooleanField(default=True, help_text='Permite acessar a tela de histÃ³rico de formulÃ¡rios.', verbose_name='Acessar tela HistÃ³rico'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Compatibilidade com versÃµes anteriores.', verbose_name='Pode editar (legado)'),
        ),
    ]
