# Generated by Django 4.2.28 on 2026-03-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_portal_roles(apps, schema_editor):
    PortalUserAccess = apps.get_model('inspecoes', 'PortalUserAccess')
    for access in PortalUserAccess.objects.select_related('user').all():
        user = access.user
        if getattr(user, 'is_superuser', False):
            access.role = 'master'
        elif access.can_edit_forms or access.can_edit:
            access.role = 'technician'
        else:
            access.role = 'viewer'
        access.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecoes', '0007_portaluseraccess_can_edit_forms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_submissions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Criado por',
            ),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='validation_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='role',
            field=models.CharField(
                choices=[
                    ('technician', 'Técnico'),
                    ('validator', 'Validador'),
                    ('viewer', 'Visualizador'),
                    ('master', 'Master'),
                ],
                default='viewer',
                help_text='Perfil operacional no portal: Técnico, Validador, Visualizador ou Master.',
                max_length=20,
                verbose_name='Perfil',
            ),
        ),
        migrations.RunPython(backfill_portal_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Rascunho'),
                    ('pending_validation', 'Pendente validação'),
                    ('rework_required', 'Refação solicitada'),
                    ('approved', 'Aprovado'),
                    ('sent_to_sap', 'Enviado SAP'),
                ],
                default='draft',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_edit',
            field=models.BooleanField(
                default=False,
                help_text='Compatibilidade com versões anteriores.',
                verbose_name='Pode editar (legado)',
            ),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_edit_forms',
            field=models.BooleanField(
                default=False,
                help_text='Compatibilidade com versões anteriores.',
                verbose_name='Editar formulários (legado)',
            ),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_view_deadlines',
            field=models.BooleanField(
                default=True,
                help_text='Compatibilidade com versões anteriores.',
                verbose_name='Acessar tela Prazos (legado)',
            ),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_view_forms',
            field=models.BooleanField(
                default=True,
                help_text='Compatibilidade com versões anteriores.',
                verbose_name='Acessar tela Formulários (legado)',
            ),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_view_history',
            field=models.BooleanField(
                default=True,
                help_text='Compatibilidade com versões anteriores.',
                verbose_name='Acessar tela Histórico (legado)',
            ),
        ),
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('form_pending_validation', 'Formulário pendente validação'),
                            ('form_approved', 'Formulário aprovado'),
                            ('form_rework', 'Formulário para refação'),
                            ('deadline_alert', 'Alerta de prazo'),
                        ],
                        max_length=40,
                        verbose_name='Categoria',
                    ),
                ),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=180, verbose_name='Chave de deduplicação')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                (
                    'equipment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='notifications',
                        to='inspecoes.equipment',
                        verbose_name='Equipamento',
                    ),
                ),
                (
                    'submission',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='notifications',
                        to='inspecoes.formsubmission',
                        verbose_name='Formulário',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='portal_notifications',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuário',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(
                condition=models.Q(('dedupe_key', ''), _negated=True),
                fields=('user', 'dedupe_key'),
                name='unique_notification_dedupe_per_user',
            ),
        ),
    ]
