# Generated by Django 4.2.28 on 2026-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0008_formsubmission_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='expanded_uncertainty_calc_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Incerteza expandida calculada (%)'),
        ),
    ]
