# Generated by Django 4.2.28 on 2026-03-10 14:32

from django.db import migrations, models
import django.db.models.deletion


def seed_default_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    Equipment = apps.get_model('inspecoes', 'Equipment')
    FormSubmission = apps.get_model('inspecoes', 'FormSubmission')

    default_form_type, _ = InspectionFormType.objects.get_or_create(
        code='FOR 08.05.003',
        defaults={
            'title': 'Verificacao e ajuste de balanca dinamica (MVP)',
            'description': 'Formulario inicial do portal para balancas dinamicas.',
            'active': True,
        },
    )

    through_model = Equipment.inspection_form_types.through
    for equipment_id in Equipment.objects.values_list('id', flat=True):
        through_model.objects.get_or_create(
            equipment_id=equipment_id,
            inspectionformtype_id=default_form_type.id,
        )

    FormSubmission.objects.filter(form_type__isnull=True).update(form_type_id=default_form_type.id)


def unseed_default_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.filter(code='FOR 08.05.003').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0009_formsubmission_expanded_uncertainty_calc_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Codigo')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de formulario',
                'verbose_name_plural': 'Tipos de formulario',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='inspection_form_types',
            field=models.ManyToManyField(blank=True, help_text='Selecione os formularios que podem ser aplicados neste equipamento.', related_name='equipments', to='inspecoes.inspectionformtype', verbose_name='Formularios habilitados'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='inspecoes.inspectionformtype', verbose_name='Formulario'),
        ),
        migrations.RunPython(seed_default_form_type, reverse_code=unseed_default_form_type),
    ]
