# Generated by Django 4.2.28 on 2026-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0010_inspectionformtype_equipment_inspection_form_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='belt_replaced',
            field=models.BooleanField(default=False, verbose_name='Houve troca de correia?'),
        ),
    ]
