# Generated by Django 4.2.28 on 2026-03-11 22:20

from django.db import migrations, models


def _forward_update_rework_notifications(apps, schema_editor):
    PortalNotification = apps.get_model('inspecoes', 'PortalNotification')
    queryset = PortalNotification.objects.filter(category='form_rework')
    for notification in queryset.iterator():
        original_title = notification.title or ''
        original_message = notification.message or ''

        new_title = original_title.replace(
            'Refação solicitada - OM ',
            'Formulário reprovado - Refazer visita - OM ',
        ).replace(
            'Refacao solicitada - OM ',
            'Formulário reprovado - Refazer visita - OM ',
        )
        new_message = original_message.replace(
            'precisa ser refeito.',
            'foi reprovado e precisa de nova visita.',
        ).replace(
            'precisa ser refeita.',
            'foi reprovado e precisa de nova visita.',
        )

        if new_title != original_title or new_message != original_message:
            notification.title = new_title
            notification.message = new_message
            notification.save(update_fields=['title', 'message', 'updated_at'])


def _reverse_update_rework_notifications(apps, schema_editor):
    PortalNotification = apps.get_model('inspecoes', 'PortalNotification')
    queryset = PortalNotification.objects.filter(category='form_rework')
    for notification in queryset.iterator():
        original_title = notification.title or ''
        original_message = notification.message or ''

        old_title = original_title.replace(
            'Formulário reprovado - Refazer visita - OM ',
            'Refação solicitada - OM ',
        )
        old_message = original_message.replace(
            'foi reprovado e precisa de nova visita.',
            'precisa ser refeito.',
        )

        if old_title != original_title or old_message != original_message:
            notification.title = old_title
            notification.message = old_message
            notification.save(update_fields=['title', 'message', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0011_formsubmission_belt_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalnotification',
            name='category',
            field=models.CharField(
                choices=[
                    ('form_pending_validation', 'Formulário pendente validação'),
                    ('form_approved', 'Formulário aprovado'),
                    ('form_rework', 'Formulário para refazer'),
                    ('deadline_alert', 'Alerta de prazo'),
                ],
                max_length=40,
                verbose_name='Categoria',
            ),
        ),
        migrations.RunPython(
            _forward_update_rework_notifications,
            _reverse_update_rework_notifications,
        ),
    ]
