# Generated by Django 4.2.28 on 2026-03-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0012_update_portalnotification_rework_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluseraccess',
            name='visible_equipments',
            field=models.ManyToManyField(blank=True, help_text='Para perfil Técnico, selecione os equipamentos que este usuário pode enxergar. Se deixar vazio, o técnico enxerga todos.', related_name='portal_user_accesses', to='inspecoes.equipment', verbose_name='Equipamentos visíveis (técnico)'),
        ),
    ]
