# Generated by Django 4.2.28 on 2026-03-12 14:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def seed_equipment_form_criteria(apps, schema_editor):
    Equipment = apps.get_model('inspecoes', 'Equipment')
    EquipmentFormCriteria = apps.get_model('inspecoes', 'EquipmentFormCriteria')
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')

    default_form_type = InspectionFormType.objects.filter(code='FOR 08.05.003').first()

    for equipment in Equipment.objects.all().iterator():
        form_types = list(equipment.inspection_form_types.all())
        if not form_types and default_form_type:
            form_types = [default_form_type]

        for form_type in form_types:
            EquipmentFormCriteria.objects.get_or_create(
                equipment_id=equipment.id,
                form_type_id=form_type.id,
                defaults={
                    'acceptance_criterion_value': (
                        equipment.acceptance_criterion_pct
                        if equipment.acceptance_criterion_pct is not None
                        else Decimal('1.0')
                    ),
                    'acceptance_criterion_unit': '%',
                    'expanded_uncertainty_value': equipment.expanded_uncertainty_pct,
                    'expanded_uncertainty_unit': '%',
                },
            )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0013_portaluseraccess_visible_equipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFormCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_criterion_value', models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Criterio de aceitacao')),
                ('acceptance_criterion_unit', models.CharField(choices=[('%', '%'), ('cm', 'cm')], default='%', max_length=8, verbose_name='Unidade do criterio')),
                ('expanded_uncertainty_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Incerteza expandida')),
                ('expanded_uncertainty_unit', models.CharField(choices=[('%', '%'), ('cm', 'cm')], default='%', max_length=8, verbose_name='Unidade da incerteza')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_criteria_configs', to='inspecoes.equipment', verbose_name='Equipamento')),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_criteria_configs', to='inspecoes.inspectionformtype', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Configuracao de criterio por formulario',
                'verbose_name_plural': 'Configuracoes de criterio por formulario',
                'ordering': ['equipment__tag', 'form_type__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentformcriteria',
            constraint=models.UniqueConstraint(fields=('equipment', 'form_type'), name='unique_equipment_form_criteria_config'),
        ),
        migrations.RunPython(seed_equipment_form_criteria, noop_reverse),
    ]
