# Generated by Django 4.2.28 on 2026-03-12 18:44

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def create_level_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.get_or_create(
        code='FOR 07.04.01.002',
        defaults={
            'title': 'Verificação e ajuste de transmissor de nível de tanque (MVP)',
            'description': 'Formulário para verificação metrológica de transmissor de nível de tanque.',
            'active': True,
        },
    )


def reverse_create_level_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.filter(code='FOR 07.04.01.002').delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecoes', '0014_equipmentformcriteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('cm', 'cm')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('cm', 'cm')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vl_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vl_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vl_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vl_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vm_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vm_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vm_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_after_vm_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vl_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vl_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vl_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vl_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vm_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vm_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vm_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_before_vm_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_coverage_factor_k',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('2.000'), max_digits=8, null=True, verbose_name='Fator de abrangencia k'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_resolution_instrument_m',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.010'), max_digits=12, null=True, verbose_name='Resolucao do instrumento (m)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='level_resolution_tape_m',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.001'), max_digits=12, null=True, verbose_name='Resolucao da trena (m)'),
        ),
        migrations.RunPython(create_level_form_type, reverse_create_level_form_type),
    ]
