# Generated by Django 4.2.28 on 2026-03-12 19:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecoes', '0016_alter_equipment_acceptance_criterion_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.0'), help_text='Limite de aceitação para o erro final (%). Ex.: 1,0', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Critério de aceitação (%)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Informe um ou mais e-mails separados por vírgula, ponto e vírgula ou quebra de linha.', verbose_name='E-mails para notificação'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='revisit_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de dias para nova verificação/ajuste do equipamento.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Periodicidade da nova visita (dias)'),
        ),
        migrations.AlterField(
            model_name='equipmentformcriteria',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AlterField(
            model_name='equipmentformcriteria',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=6, verbose_name='Critério de aceitação (%)'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='om_number',
            field=models.CharField(max_length=50, verbose_name='Nº OM'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='sap_status',
            field=models.CharField(choices=[('not_started', 'Não iniciado'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='not_started', max_length=24),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending_validation', 'Pendente validação'), ('rework_required', 'Refação solicitada'), ('approved', 'Aprovado'), ('sent_to_sap', 'Enviado SAP')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='category',
            field=models.CharField(choices=[('form_pending_validation', 'Formulário pendente validação'), ('form_approved', 'Formulário aprovado'), ('form_rework', 'Formulário para refazer'), ('deadline_alert', 'Alerta de prazo')], max_length=40, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Chave de deduplicação'),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inspecoes.formsubmission', verbose_name='Formulário'),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Compatibilidade com versões anteriores.', verbose_name='Pode editar (legado)'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_edit_forms',
            field=models.BooleanField(default=False, help_text='Compatibilidade com versões anteriores.', verbose_name='Editar formulários (legado)'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_view_deadlines',
            field=models.BooleanField(default=True, help_text='Compatibilidade com versões anteriores.', verbose_name='Acessar tela Prazos (legado)'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_view_forms',
            field=models.BooleanField(default=True, help_text='Compatibilidade com versões anteriores.', verbose_name='Acessar tela Formulários (legado)'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='can_view_history',
            field=models.BooleanField(default=True, help_text='Compatibilidade com versões anteriores.', verbose_name='Acessar tela Histórico (legado)'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='registration',
            field=models.CharField(blank=True, help_text='Se vazio, usa o username do usuário.', max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='role',
            field=models.CharField(choices=[('technician', 'Técnico'), ('validator', 'Validador'), ('viewer', 'Visualizador'), ('master', 'Master')], default='viewer', help_text='Perfil operacional no portal: Técnico, Validador, Visualizador ou Master.', max_length=20, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='portaluseraccess',
            name='visible_equipments',
            field=models.ManyToManyField(blank=True, help_text='Para perfil Técnico, selecione os equipamentos que este usuário pode enxergar. Se deixar vazio, o técnico enxerga todos.', related_name='portal_user_accesses', to='inspecoes.equipment', verbose_name='Equipamentos visíveis (técnico)'),
        ),
    ]
