# Generated by Django 4.2.28 on 2026-03-16 18:56

from decimal import Decimal
from django.db import migrations, models


def create_scanner_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.get_or_create(
        code='FOR SCANNER',
        defaults={
            'title': 'Validação de certificado de calibração de scanner (MVP)',
            'description': 'Formulário para análise metrológica de certificado de calibração de scanner.',
            'active': True,
        },
    )


def reverse_create_scanner_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.filter(code='FOR SCANNER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0018_convert_level_units_cm_to_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='scanner_certificates/', verbose_name='Certificado de calibração (PDF)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_certificate_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_k_factor',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('2'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_manufacturer_ppm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('10'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measured_1_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measured_2_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measured_3_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measured_4_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measured_5_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measured_6_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_measurement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_nominal_1_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_nominal_2_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_nominal_3_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_nominal_4_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_nominal_5_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_nominal_6_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_target_1',
            field=models.CharField(blank=True, default='Refletor 1', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_target_2',
            field=models.CharField(blank=True, default='Refletor 2', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_target_3',
            field=models.CharField(blank=True, default='Refletor 3', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_target_4',
            field=models.CharField(blank=True, default='Refletor 4', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_target_5',
            field=models.CharField(blank=True, default='Refletor 5', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_target_6',
            field=models.CharField(blank=True, default='Refletor 6', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_u_env_mm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_u_ref_mm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_u_rep_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_u_res_mm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='scanner_u_setup_mm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentformcriteria',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AlterField(
            model_name='equipmentformcriteria',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
        migrations.RunPython(create_scanner_form_type, reverse_create_scanner_form_type),
    ]
