# Generated by Django 4.2.28 on 2026-03-23 14:10

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def backfill_equipment_criterion_unit(apps, schema_editor):
    Equipment = apps.get_model('inspecoes', 'Equipment')
    EquipmentFormCriteria = apps.get_model('inspecoes', 'EquipmentFormCriteria')

    for equipment in Equipment.objects.all().iterator():
        configs = EquipmentFormCriteria.objects.filter(equipment_id=equipment.id).order_by('id')
        first_config = configs.first()
        if not first_config:
            continue

        distinct_units = list(configs.values_list('acceptance_criterion_unit', flat=True).distinct())
        target_unit = first_config.acceptance_criterion_unit or equipment.acceptance_criterion_unit or '%'
        target_value = first_config.acceptance_criterion_value

        if len(distinct_units) == 1 and distinct_units[0]:
            target_unit = distinct_units[0]

        update_fields = []
        if equipment.acceptance_criterion_unit != target_unit:
            equipment.acceptance_criterion_unit = target_unit
            update_fields.append('acceptance_criterion_unit')
        if target_value is not None and equipment.acceptance_criterion_pct != target_value:
            equipment.acceptance_criterion_pct = target_value
            update_fields.append('acceptance_criterion_pct')

        if update_fields:
            equipment.save(update_fields=update_fields)


def reverse_backfill_equipment_criterion_unit(apps, schema_editor):
    # No-op rollback: keep persisted values.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0019_formsubmission_scanner_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='acceptance_criterion_unit',
            field=models.CharField(
                choices=[('%', '%'), ('m', 'm'), ('mm', 'mm')],
                default='%',
                help_text='Unidade do criterio padrao do equipamento (% , m ou mm).',
                max_length=8,
                verbose_name='Unidade do criterio padrao',
            ),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_pct',
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal('1.0'),
                help_text='Limite padrao de aceitacao do equipamento. Ex.: 1,0 (%, m ou mm).',
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal('0.001'))],
                verbose_name='Criterio padrao',
            ),
        ),
        migrations.RunPython(backfill_equipment_criterion_unit, reverse_backfill_equipment_criterion_unit),
    ]
