# Generated by Django 4.2.28 on 2026-03-23 14:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0020_equipment_acceptance_criterion_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.0'), help_text='Limite padrão de aceitação do equipamento. Ex.: 1,0 (%, m ou mm).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Critério padrão'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm')], default='%', help_text='Unidade do critério padrão do equipamento (% , m ou mm).', max_length=8, verbose_name='Unidade do critério padrão'),
        ),
    ]
