# Generated by Django 4.2.28 on 2026-03-23 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecoes', '0021_alter_equipment_acceptance_criterion_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='assigned_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions_to_validate', to=settings.AUTH_USER_MODEL, verbose_name='Validador designado'),
        ),
    ]
