# Generated by Django 4.2.28 on 2026-03-26 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0022_formsubmission_assigned_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='validation_deadline_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prazo de validação (dias)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='validation_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de validação até'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='validation_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado para validação em'),
        ),
        migrations.AddField(
            model_name='portaluseraccess',
            name='validator_deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='Prazo em dias para validar formulários atribuídos a este usuário (perfil Validador). Se vazio, usa o padrão do sistema.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prazo para validação (dias)'),
        ),
    ]
