# Generated by Django 4.2.28 on 2026-03-26 17:12

from django.db import migrations, models


def create_flow_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.get_or_create(
        code='FOR VAZAO',
        defaults={
            'title': 'Validação de certificado de calibração de medidor de vazão (MVP)',
            'description': 'Formulário para análise metrológica de certificado de calibração de medidor de vazão.',
            'active': True,
        },
    )


def reverse_create_flow_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.filter(code='FOR VAZAO').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0023_formsubmission_validation_deadline_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_1_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_2_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_3_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_4_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_5_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_6_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_range_max_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_calibration_range_min_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='flow_certificates/', verbose_name='Certificado de calibração (PDF)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_certificate_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_converter_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_converter_serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_indicated_1_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_indicated_2_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_indicated_3_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_indicated_4_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_indicated_5_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_indicated_6_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_k_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_k_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_k_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_k_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_k_5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_k_6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_measurement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_meter_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_meter_serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_point_label_1',
            field=models.CharField(blank=True, default='Ponto 1', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_point_label_2',
            field=models.CharField(blank=True, default='Ponto 2', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_point_label_3',
            field=models.CharField(blank=True, default='Ponto 3', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_point_label_4',
            field=models.CharField(blank=True, default='Ponto 4', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_point_label_5',
            field=models.CharField(blank=True, default='Ponto 5', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_point_label_6',
            field=models.CharField(blank=True, default='Ponto 6', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_reference_1_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_reference_2_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_reference_3_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_reference_4_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_reference_5_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_reference_6_m3h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tag_on_certificate',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tendency_1_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tendency_2_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tendency_3_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tendency_4_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tendency_5_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_tendency_6_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_uncertainty_1_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_uncertainty_2_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_uncertainty_3_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_uncertainty_4_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_uncertainty_5_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_uncertainty_6_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.RunPython(create_flow_form_type, reverse_create_flow_form_type),
    ]
