# Generated by Django 4.2.28 on 2026-03-27 14:24

from decimal import Decimal
from django.db import migrations, models


def create_flow_adjust_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.get_or_create(
        code='FOR 08.05.006',
        defaults={
            'title': 'Verificacao e ajuste de medidores de vazao (MVP)',
            'description': 'Formulario para verificacao e ajuste de medidor de vazao com calculo automatico de incerteza expandida.',
            'active': True,
        },
    )


def reverse_create_flow_adjust_form_type(apps, schema_editor):
    InspectionFormType = apps.get_model('inspecoes', 'InspectionFormType')
    InspectionFormType.objects.filter(code='FOR 08.05.006').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0024_formsubmission_flow_calibration_1_m3h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_after_totmv_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_after_totmv_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_after_totmv_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_after_totsup_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_after_totsup_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_after_totsup_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_before_totmv_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_before_totmv_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_before_totmv_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_before_totsup_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_before_totsup_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_before_totsup_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_circumference_ci_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_k_factor',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('2.000'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_pipe_nominal_in',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_thickness_1_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_thickness_2_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_thickness_3_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_thickness_4_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_u_ci_mm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_u_delta_t_s',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('5.000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_u_dut_repeat_pct',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_u_dut_res_pct',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='flow_adjust_u_inst_t_mm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.200'), max_digits=12, null=True),
        ),
        migrations.RunPython(create_flow_adjust_form_type, reverse_create_flow_adjust_form_type),
    ]
