# Generated by Django 4.2.28 on 2026-03-30 11:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0025_formsubmission_flow_adjust_after_totmv_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80, unique=True, verbose_name='TAG do aferidor')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('nominal_volume_l', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volume nominal (L)')),
                ('graduation_l', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Usado no cálculo de incerteza de volume (u_volume = graduação / √12).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Graduação (L)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Aferidor de volume',
                'verbose_name_plural': 'Aferidores de volume',
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_empty_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_empty_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_empty_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_full_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_full_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_full_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_high_count_cts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_high_point_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_low_count_cts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_low_point_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_mds_informed_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_mds_reading_1_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_mds_reading_2_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_mds_reading_3_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_mds_reading_4_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_mds_reading_5_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_volume_1_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_volume_2_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_after_volume_3_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_empty_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_empty_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_empty_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_full_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_full_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_full_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_high_count_cts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_high_point_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_low_count_cts',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_low_point_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_mds_informed_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_mds_reading_1_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_mds_reading_2_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_mds_reading_3_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_mds_reading_4_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_mds_reading_5_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_volume_1_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_volume_2_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_before_volume_3_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_k_factor',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('2.000'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_mds_resolution_gcm3',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0010'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_scale_criterion_pct',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.000'), max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_scale_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='density_related_submissions', to='inspecoes.equipment', verbose_name='Balança estática utilizada'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_scale_mab_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_scale_mib_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_scale_u_additional_kg',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_volume_graduation_l',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0100'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_standard_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='density_submission_standard_1', to='inspecoes.volumestandard', verbose_name='Aferidor 1'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_standard_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='density_submission_standard_2', to='inspecoes.volumestandard', verbose_name='Aferidor 2'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='density_standard_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='density_submission_standard_3', to='inspecoes.volumestandard', verbose_name='Aferidor 3'),
        ),
    ]
