# Generated by Django 4.2.28 on 2026-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0026_volumestandard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='density_static_scales',
            field=models.ManyToManyField(blank=True, help_text='Para equipamentos densímetro (FOR 08.03.003), selecione as balanças estáticas permitidas no procedimento.', related_name='used_as_density_scale_for', to='inspecoes.equipment', verbose_name='Balanças estáticas vinculadas (densímetro)'),
        ),
    ]
