# Generated by Django 4.2.28 on 2026-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0027_equipment_density_static_scales'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='truck_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='truck_scale_certificates/', verbose_name='Certificado de calibração (PDF)'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_certificate_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_4_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_5_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_6_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_factor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_4_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_5_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_6_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_measurement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_1',
            field=models.CharField(blank=True, default='Ponto 1', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_2',
            field=models.CharField(blank=True, default='Ponto 2', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_3',
            field=models.CharField(blank=True, default='Ponto 3', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_4',
            field=models.CharField(blank=True, default='Ponto 4', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_5',
            field=models.CharField(blank=True, default='Ponto 5', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_6',
            field=models.CharField(blank=True, default='Ponto 6', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_4_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_5_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_6_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_tag_on_certificate',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_declared_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm'), ('kg', 'kg')], default='%', help_text='Unidade do critério padrão do equipamento (% , m ou mm).', max_length=8, verbose_name='Unidade do critério padrão'),
        ),
        migrations.AlterField(
            model_name='equipmentformcriteria',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm'), ('kg', 'kg')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AlterField(
            model_name='equipmentformcriteria',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm'), ('kg', 'kg')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='acceptance_criterion_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm'), ('kg', 'kg')], default='%', max_length=8, verbose_name='Unidade do criterio'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='expanded_uncertainty_unit',
            field=models.CharField(choices=[('%', '%'), ('m', 'm'), ('mm', 'mm'), ('kg', 'kg')], default='%', max_length=8, verbose_name='Unidade da incerteza'),
        ),
    ]
