# Generated by Django 4.2.28 on 2026-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0028_formsubmission_truck_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_10_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_11_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_12_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_7_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_8_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_error_9_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_10_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_11_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_12_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_7_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_8_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_load_9_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_10',
            field=models.CharField(blank=True, default='Ponto 10', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_11',
            field=models.CharField(blank=True, default='Ponto 11', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_12',
            field=models.CharField(blank=True, default='Ponto 12', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_7',
            field=models.CharField(blank=True, default='Ponto 7', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_8',
            field=models.CharField(blank=True, default='Ponto 8', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_point_label_9',
            field=models.CharField(blank=True, default='Ponto 9', max_length=120),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_10_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_11_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_12_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_7_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_8_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_reading_9_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
