# Generated by Django 4.2.28 on 2026-03-31 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0029_formsubmission_truck_error_10_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentformcriteria',
            name='certificate_points_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Opcional. Usado no FOR RODOVIARIA para definir quantos pontos exibir/preencher (1 a 12).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Limite de pontos do certificado'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_points_limit',
            field=models.PositiveSmallIntegerField(default=12, help_text='Quantidade de pontos exibidos no FOR RODOVIARIA (1 a 12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
