# Generated by Django 4.2.28 on 2026-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0031_create_humidity_certificate_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_10',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_11',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_12',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_6',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_7',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_8',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_k_9',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_10_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_11_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_12_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_1_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_2_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_3_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_4_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_5_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_6_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_7_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_8_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='truck_uncertainty_9_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
